CREATE TABLE IF NOT EXISTS twitter(
    id SERIAL PRIMARY KEY,
    user_id text,
    user_name text,
    user_href text,
    user_handle text,
    user_avatar_href text,
    tweet_id text,
    tweet_item_id text,
    tweet_conversation_id text,
    tweet_text_html text,
    tweet_time date,
    tweet_nonce text,
    tweet_language text,
    tweet_timestamp timestamp,
    tweet_permalink text,
    mentions_count bigint,
    retweets_count bigint,
    favorites_count bigint,
    is_reply boolean,
    is_retweet boolean,
    has_media boolean,
    has_mentions boolean,
    has_quote_tweet boolean
);